[[chapter1]]
== Kapitel 1

=== Die wichtigste Heilung

Im Anfang schuf Gott Himmel und Erde. Und alles war vollkommen.
Es gab Adam und Eva. Es gab die Tiere. Es gab eine vollkommene
Übereinstimmung zwischen der ganzen Schöpfung.
Es gab uneingeschränkte Verständigung zwischen Gott und Mensch.

Und dann kam durch Adams und Evas Entscheidung,
Gottes Gebot nicht zu gehorchen, die Sünde in die Welt.
Und als die Sünde in die Welt kam, brachte sie den Tod mit sich.
Und mit dem Tod kam die Krankheit.

Heute gibt es viele Formen und Manifestationen von Krankheit.
Es gibt die Krankheit des Verstandes, Krankheit des Herzens,
Krankheit des Körpers.

Aber die wichtigste von allen ist die Krankheit der Seele.
Und jeder Mensch wird mit dieser Krankheit geboren.
Sie ist ein direktes Ergebnis von Adams und Evas Ungehorsam.
Genau dies begann in unserer Welt, als Adam und Eva Gott nicht gehorchten.
Krankheit kam durch Sünde.

Wir wurden alle geboren mit der Krankheit der Sünde.
Und wichtiger als eine Heilung des Körpers, der Gedanken oder Gefühle,
die Du  empfangen möchtest, ist die Heilung der Seele.


Und das Beste dabei: Du kannst genau jetzt in diesem Augenblick
von Sünde geheilt werden; denn Jesus, der Sohn Gottes,
hat dies durch seinen Tod und seine Auferstehung ermöglicht...

Es braucht keine spezielle Formel. Es muss kein geheimnisvoller Augenblick sein.
Niemand muss Dir die Hände auflegen. Es geschieht zwischen Dir und Gott.
Es braucht lediglich ein einfaches Gebet aus Deinem Herzen zu Gott,
etwa so:

"`_Gott, ich bekenne, dass ich gesündigt habe.
Ich habe Deinen Geboten nicht gehorcht und habe kein heiliges Leben geführt.
Ich bereue das. Ich bitte Dich, mich mit Deiner Gegenwart zu füllen.
Ich glaube, dass Yeshua (Jesus) Dein Sohn ist und Du Ihn für mich gesandt
und als Opfer für mich gegeben hast.
Er starb und ist wieder auferstanden und damit hat er den Tod überwunden.
Ich lege mein Vertrauen für meine ewige Errettung in ihn.
Heile die Krankheit meiner Seele.
Befreie mich aus dem Gefängnis der Sünde. Amen._`"


Wenn Du dieses Gebet oder ein ähnliches gebetet hast,
*wurdest Du von der Krankheit Deiner Seele geheilt.*
Du bist nicht länger an Sünde gebunden.
Du bist nicht länger Teil dieser Welt. Und das Beste von allem:
Gottes Verheißungen für seine Kinder
(Gläubige, die Jesus  akzeptiert haben wie Du,
als Du dieses Gebet gesprochen hast) gelten für DICH.

[quote, Kent W.]
--
*Erlebte Heilung in der Gegenwart*

"`Bei meiner Frau wurde Nierenkrebs und akute Knochenmark-Leukämie
diagnostiziert. Die Ärzte gaben ihr 30% Überlebens-Chance...
Jetzt ist sie zu 100% geheilt.`"
--

In diesem Buch geht es um Gottes Verheißungen.
Es ist von eminenter Wichtigkeit, dass Du Gottes Wort über Deinem
Leben betest und aussprichst, um Glauben an seine
uneingeschränkte Kraft zu haben.

Behandle dieses Buch nicht wie eine eingleisige Unterhaltung.
Dafür ist es nicht gedacht. Dieses Buch dient dazu,
eine Unterhaltung mit Gott in Gang zu bringen -
zu ihm mit seinen eigenen Worten zu sprechen, die Dir als Gläubigem gelten.

Gott sprach Worte und erschuf die Welt und alles darin.
In seinem Wort (der Bibel) ist unbeschränkte Kraft.
Und wenn Du anfängst, seine Verheißungen zu bekennen und zu glauben,
wird Dir nichts unmöglich sein.

Leute fragen mich, nachdem ich mehr als 40 Jahre die Bibel in Bezug
auf ihre Heilungszusagen studiert habe:
"`Welche Sache hättest Du gern bereits vor 40 Jahren  gewusst?`"

Ich wünschte, ich hätte verstanden,
wie ich meinen Glauben anwenden kann, wenn die Heilung nicht sofort
sichtbar wird. Die Bibel macht es deutlich,
aber ich hatte Schuppen vor meinen Augen,
die die Wahrheit viele Jahre von mir fernhielten.

[quote, Lisa K.]
--
*Erlebte Heilung in der Gegenwart*

"`Der Herr hat mich von Alkohol- und Zigarettensucht völlig freigesetzt,
keine Entzugserscheinungen.
Er hat mich vollständig befreit.`"
--

Markus 11:23.24 sagt: "`Wahrlich, ich sage euch: Wer zu diesem Berg
(oder zu seiner Krankheit) sagen wird: Hebe dich empor und
wirf dich ins Meer! und nicht zweifeln wird in seinem Herzen,
sondern glaubt, dass geschieht, was er sagt, dem wird es werden.
Darum sage ich euch: Alles, um was ihr auch betet und bittet,
glaubt, dass ihr es empfangen habt (im Griechischen: `nehmt`),
und es wird euch werden`" (angepasst).

Du musst die Verheißungen Gottes _nehmen_, bevor Du sie sehen kannst.
Das ist der Unterschied zwischen einer Heilung und einem Wunder.
Ein Wunder ist eine sofortige Heilung und
eine Heilung ist ein schrittweises Wunder.

Die Verheißungen Gottes sind wie eine Saat in der natürlichen Welt.
Wenn die Saat gepflanzt ist und wir sie nicht wieder ausreißen
und wir das Unkraut entfernen, dann hoffen wir nicht nur,
dass sie wachsen wird, wir wissen es! Aber oft sind wir geneigt,
die Saat seiner Verheißungen auszureißen oder durch Unkraut
unseren Glauben in sie niederhalten zu lassen.
Wir reißen die Saat von Gottes Verheißungen aus,
indem wir unseren Symptomen glauben, aber nicht dem Wort Gottes.
Wir lassen Unkraut unseren Glauben in seine Verheißungen vernichten,
indem wir Haltungen wie Unversöhnlichkeit (Markus 11:25.26)
und andere unvergebene Sünden in unserem Leben Wurzeln schlagen lassen.

Einen Glauben zu haben, wie die Bibel ihn beschreibt,
ist sogar noch eine stärkere Art von Glauben, als etwas zu glauben,
bevor man es sieht. Du musst offensiv Deine Heilung ergreifen,
egal wie lange es dauert, bis sie von der unsichtbaren
in die sichtbare Welt durchdringt. Jesus beschreibt es folgendermaßen
in Matthäus 11:12: "`Aber von den Tagen Johannes des Täufers an
bis jetzt wird dem Reich der Himmel Gewalt angetan,
und Gewalttuende reißen es an sich`".
In anderen Worten, der Kampf findet in Deinem Kopf statt.

Du musst gewaltsam jeden Gedanken und jede Vorstellung niederreißen,
die dem Wort Gottes widerspricht. Das bedeutet nicht,
dass Du die Symptome verleugnest. Du verweigerst den Symptomen das Recht,
zu bleiben und ein Anrecht an Deinem Leben zu haben.
Werde gewalttätig und befiehl ihnen zu gehen.
Symptome, die der Teufel hervorruft, werden so lange bleiben,
bis ihnen deutlich ist, Du wirst nicht aufgeben!

Durch den Glauben rufe die Dinge, die nicht sind,
als ob sie seien: [wie Gott] "`das Nichtseiende ruft, als wäre es da`" (Römer 4:17).

Das ist nicht einfach positives Denken. Du wirst lernen,
wenn Du Dich durch dieses Buch arbeitest,
dass das Meditieren über Gottes Wort mehr ist,
als einfach Worte zu sagen.

Über Gottes Wort zu meditieren bedeutet, Seine Verheißungen durch
Sein eigenes Wort in Existenz zu sprechen.

Es ist kein Ritual &#8212; es bedeutet, Du glaubst wahrhaftig in Deinem
Herzen die Verheißungen, die Du bekennst.

Ich hatte das Vorrecht, Kathryn Kuhlman zu kennen und
ihren Dienst zu erleben, den großartigsten Wunderdienst des
20. Jahrhunderts. Sie prophezeite, dass es nach ihrem Tod
eine große Ausgießung von Gottes Geist geben wird.
Dieses dritte große Erwachen würde so kraftvoll sein,
dass in einem Krankenhaus jeder geheilt werden würde.

Ich erlebe das heute und noch Größeres. Ich sehe kreative Wunder,
wo Menschen neue Hüften und andere Körperteile empfangen.
Du und ich leben in der heutigen Zeit, um in diesem großen
Erwachen gebraucht zu werden, das über unseren Planeten kommen wird.
Und wir werden nicht nur beobachten. Gott wird durch uns wirken,
um es aus der unsichtbaren in die sichtbare Welt zu bringen.

[quote, Patti T.]
--
*Erlebte Heilung in der Gegenwart*

"`Während ich Krebs hatte, haben mir die Ärzte gesagt,
ich solle meine Angelegenheiten regeln, aber Gott sagte zu
mir: `Nein, fürchte Dich nicht. Ich bin mit Dir.`
Das Ergebnis: Keine Chemo, keine Bestrahlung. Ich bin krebsfrei.
Gott ist ein gewaltiger Gott.`"
--

Die übernatürliche Kraft des Himmels wird auf diese Erde ausgegossen
wie nie zuvor. Wir kommen in eine Epoche der Zeitgeschichte,
in der die größeren Wunder normal sein werden (Joh. 14:12).

Aber erinnere Dich immer daran:
Du wurdest von der ultimativen Krankheit geheilt
(der Krankheit der Sünde), als Du Dich entschieden hast,
Deinen Glauben in Jesus zu legen und ihm für Deine Errettung zu glauben.
Vor mehr als 2000 Jahren nahm Er _alle_ Sünde, _alle_ Krankheit,
_alle_ Lasten auf sich und am Kreuz mit in den Tod.

Dann ist er auferstanden.

[quote, Janey B.]
--
*Erlebte Heilung in der Gegenwart*

"`Als Kind... hatte ich defekte Trommelfelle auf Grund
wiederkehrender Ohreninfektionen.
Gott gab mir ein neues Trommelfell für jedes Ohr.
Eine Untersuchung beim Spezialisten belegt das.`"
--
