[[chapter2]]
== Kapitel 2

=== Wie man über Schriftstellen meditiert

"`*Meditieren*`"  bedeutet in der hebräischen Sprache,
"`zu sprechen oder murmeln`". Darum ist es jüdische Gewohnheit beim Meditieren,
die Worte Gottes laut auszusprechen.
Wenn ich über Schriftstellen meditiere, tue ich das Folgende:

. Den Vers personalisieren: auf mich persönlich beziehen
-> Psalm 91:1 [personalisiert]:
"`Wer... wohnt`" [unpersonalisiert] wird zu
"`Ich wohne im Schutz...`" [personalisiert]


. Stelle Dir vor, das zu tun, was der Vers sagt.

. Sprich den Vers laut aus.

. Füge beschreibende Worte hinzu.
-> Psalm 91:1 [Beschreibende Worte]
"`Ich wohne [Ich lebe und atme die verfeinerte Luft des Himmels],
im Schutz des Höchsten...`"


Du wirst lernen, wenn Du nach jüdischer Gewohnheit über Gottes Wort meditierst,
dass Du die Worte nicht nur laut aussprichst, sondern sie auch in Deinem Herzen glaubst.
Sprich laut zu Deinem Berg (den Symptomen) und dann handle nach Deinem Glauben!

Wenn Du Jesus nicht wirklich kennst, ist das Meditieren über der Schrift nur eine
religiöse Übung. Um Gott zu erleben, musst Du glauben, dass er Jesus gesandt hat,
um für Deine Sünden zu sterben, und musst ihn laut bekennen als Deinen Herrn und
Retter und ihn bitten, in Dir zu leben.

Du empfängst tieferes Wissen und Erfahrung, wenn Du täglich die Bibel liest,
täglich in Sprachen betest und ein Leben des Lobpreises und der Anbetung führst,
indem Du Dir ständig bewusst machst, dass der Messias in Dir lebt,
Dich liebt und Dich führt. Erfreue Dich immer an seiner Gegenwart.

Erlebe mehr von ihm jeden Tag. Mache ihn wirklich zum Herrn.
Dann wird Dir bewusst, dass *Du in ihm vollkommen heil bist!*
