[[chapter3]]
== Kapitel 3

=== Die Heilungsschriftstellen

==== Josua 1:7.8
Nur sei recht stark und mutig, dass du darauf achtest, nach dem ganzen Gesetz zu handeln,
... Weiche nicht davon ab, [weder] zur Rechten noch zur Linken, damit du [*überall*]
Erfolg hast, wo immer du gehst! Dieses Buch des Gesetzes soll nicht von deinem
Mund weichen, und du sollst *Tag und Nacht* darüber *nachsinnen*, damit du darauf achtest,
nach alledem zu handeln, was darin geschrieben ist; denn dann wirst du auf deinen
Wegen zum Ziel gelangen und dann wirst du Erfolg haben.


==== Hebräer 11:6
*Ohne Glauben* aber ist es *unmöglich*, [*ihm*] *wohlzugefallen*;
denn wer Gott naht, muss glauben, dass er ist und denen,
die ihn (fleißig) suchen, ein *Belohner* sein wird.


==== Markus 11:23.24
Würde ich zu diesem Berg sagen: Du *musst* dich empor heben und du *musst* dich ins
Meer werfen! und würde nicht zweifeln in meinem Herzen, sondern glauben,
dass geschieht, was ich sage, wird es mir werden.
Alles, worum ich auch bete und bitte, ich glaube, dass ich es empfangen habe,
und es wird mir werden.


==== Römer 10:17
...mein Glaube kommt aus der *Verkündigung*, die *Verkündigung* aber
durch das *Wort* Christi.
[Wenn ich mich selbst Gottes Wort sprechen höre, wächst mein Glaube und
*Gott hat Gefallen an mir.*]


==== Psalm 86:15
Du aber, Herr, *bist* ein barmherziger und gnädiger Gott,
langsam zum Zorn und groß an Gnade und Wahrheit.


==== Römer 4:17-21
...Gott, dem er glaubte, der ... das Nichtseiende ruft [er hat es verheißen],
wie wenn es [bereits] da wäre [Ich rufe Dinge, die nicht existieren,
als würden Sie bereits existieren]. Und nicht schwach im Glauben,
sah er [Abraham] seinen eigenen, schon erstorbenen Leib an, da er fast
hundert Jahre alt war, und das Absterben des Mutterleibes der Sara und
zweifelte nicht durch Unglauben an der *Verheißung* Gottes, sondern wurde
gestärkt im Glauben, weil er Gott die Ehre gab. Und er war *der vollen Gewißheit*,
dass er _(Gott)_, was er *verheißen* hat, auch zu tun vermöge.


==== 2. Mose 23:25.26
Und ihr sollt dem HERRN, eurem Gott, dienen [hebräisch: "`*anbeten*`"],
so wird er dein Brot und dein Wasser segnen, und ich werde *[alle] Krankheit*
aus deiner Mitte *entfernen*. Keine [Frau] in deinem Land wird eine Fehlgeburt
haben oder unfruchtbar sein; die Zahl deiner Tage werde ich *erfüllen.*

[quote, Loughrin M.]
--
*Erlebte Heilung in der Gegenwart*

"`Mein Rücken wurde durch Jahwe geheilt. Keine Medikamente, kein Chiropraktiker,
kein Arzt. Ich wurde geheilt durch gemeinsames Gebet in der Gemeinde.`"
--


==== 2. Korinther 1:20
Denn so viele Verheißungen Gottes es gibt, [*auf alle*] ist in ihm das Ja;
deshalb auch durch ihn das Amen (so sei es), Gott zur Ehre durch uns.


==== Jesaja 53:4.5
Jedoch unsere Leiden - er *hat* [sie] getragen, und unsere Schmerzen
(hebr: "`Krankheiten`") &#8212; er hat sie auf sich geladen...
und durch seine Striemen *ist mir Heilung geworden.*


==== Psalm 1:1-3
Ich bin gesegnet, denn ich habe meine Lust hat am Gesetz des HERRN und über
sein Gesetz sinne ich Tag und Nacht!

Ich bin wie ein Baum, gepflanzt an Wasserbächen, der seine Frucht bringt zu
seiner Zeit und dessen Laub nicht verwelkt; *alles, was ich tue, gelingt* mir.


[quote, Charleen S.]
--
*Erlebte Heilung in der Gegenwart*

"`Mir wurden noch sechs Wochen zu leben gegeben &#8212; vor 3 Jahren.
Aber Gott gab mir ein Wunder! Er ist immer noch im Heilungs- und Wundergeschäft.
Bete weiter und gib niemals auf!`"
--

==== Hebräer 11:1
Der *Glaube* aber ist eine *Verwirklichung* (die Bestätigung, die Besitzurkunde) dessen,
was ich hoffe, der *Beweis* von Dingen, die ich *nicht sehe*, und das *Überzeugtsein*
von ihrer Existenz [mein Glaube erkennt eine reale Tatsache, die meine Sinne nicht erkennen].


==== Apg 10:38
Jesus von Nazareth, wie Gott ihn mit Heiligem Geist und mit Kraft gesalbt hat,
der umherging und *wohltat* und *alle heilte*, die von dem Teufel überwältigt waren;
denn *Gott* war mit ihm. [Ich bin gesalbt mit Heiligem Geist und mit Kraft.
Ich tue Gutes, indem ich alle heile, die vom Teufel bedrückt werden, denn Gott ist mit mir.]


==== Matthäus 16:19
Gott hat mir die *Schlüssel* des Reiches der Himmel gegeben; und was immer ich auf der
Erde *binden* (verbieten) werde, wird in den Himmeln gebunden (verboten) sein,
und was immer ich auf der Erde *lösen* (erlauben) werde, wird in den Himmeln
gelöst (erlaubt) sein.
[Krankheit ist im Himmel bereits verboten und in Jesu Namen verbiete ich
{Name der Krankheit} in meinem Körper!]


==== Sprüche 4:20-22
Ich *achte* auf Gottes Worte, seinen Reden neige ich mein *Ohr* zu!
Ich lasse sie nicht aus meinen *Augen* weichen, ich bewahre sie im Innern
meines *Herzens*! Denn *Leben* sind sie mir, und *Heilung* für mein *ganzes* Fleisch.


==== Epheser 3:20
Dem aber, der über alles hinaus zu tun vermag, über die Maßen mehr, als ich
erbitte oder erdenke, gemäß der *Kraft*, die *in mir* wirkt, _dem sei Ehre_.


==== 2. Korinther 5:21
Den, der Sünde nicht kannte, hat er für mich zur Sünde gemacht,
damit ich Gottes Gerechtigkeit würde in ihm. [Ich bin die Gerechtigkeit Gottes in Jesus!]


==== Jesaja 54:17
*Keiner* Waffe [Krankheit ist eine Waffe des Feindes], die gegen mich geschmiedet wird,
soll es gelingen... Das ist mein Erbteil als Knecht des HERRN...


==== Johannes 10:10
Der Dieb kommt nur, um zu stehlen und zu schlachten und zu verderben
[Krankheit ist Stehlen, Töten und Verderben]. Jesus ist gekommen,
damit ich Leben habe [mich an Gesundheit erfreue] und [es in]
Überfluss habe (in Fülle, bis es überfließt).


==== Matthäus 28:18.19
Und Jesus trat zu [ihnen] und... sprach: Mir ist *alle* Macht gegeben im Himmel
und auf Erden. Geht nun hin... [Mir wurde die gleiche Autorität gegeben,
um alle Nationen zu Jüngern... zu machen].”


==== Lukas 10:19
Siehe, mir wurde die Macht gegeben, auf Schlangen und Skorpione zu treten,
und über die *ganze* Kraft des Feindes, und *nichts* soll mir schaden.

[quote, Levi F.]
--
*Erlebte Heilung in der Gegenwart*

"`Ich bin gesegnet, heute hier zu sein. Meine Mutter hatte Uteruskrebs und ihr
wurde gesagt, sie könne niemals Kinder haben. Sie betete für Heilung und
Gott gab ihr drei Kinder, mich eingeschlossen.`"
--

==== 2. Petrus 1:3.4
Da seine göttliche Kraft mir alles zum Leben [Notwendige, Wichtige] und zur
Gottseligkeit geschenkt hat durch die [volle, persönliche] Erkenntnis dessen,
der mich berufen hat...
[Ich weiß dass, weil er] mir über die Maßen große und kostbare Verheißungen
[gegeben *hat*]...


==== 1. Johannes 3:8
Hierzu ist der Sohn Gottes geoffenbart worden: damit er die Werke des
Teufels vernichte. [Ich werde Krankheit zerschlagen, indem ich ihr befehle,
im Namen Jesu zu weichen].


==== 1. Petrus 3:9
Vergeltet nicht Böses mit Bösem oder Scheltwort mit Scheltwort.
Ich werde nicht beleidigen, wenn ich beleidigt werde. Stattdessen werde ich
Segen zurückgeben. Dazu hat Gott mich berufen, und *er wird mich dafür segnen.*

==== Markus 9:23
Jesus sagt.... "`Wenn Du glauben kannst, sind *alle* Dinge möglich....`"

==== Hebräer 6:12
...durch *Glaube* und *Geduld* erbe ich die *Verheißungen.*


==== Psalm 105:37
...Und es war kein Schwacher unter seinen (des Herrn) Stämmen [Ich gehöre zu seiner Familie!].


==== Jesaja 55:10-12
Denn wie der Regen und Schnee vom Himmel fällt und nicht dahin zurückkehrt,
sondern die Erde tränkt, sie befruchtet und sie sprießen lässt, dass sie dem
Sämann Samen gibt und Brot dem Essenden, so wird Gottes Wort sein, das aus meinem
Mund hervorgeht. Es wird nicht leer zu mir zurückkehren, sondern es wird bewirken,
was ihm gefällt, und ausführen, wozu er es gesandt hat.
Denn in Freuden werde ich ausziehen und in Frieden [Ganzheit/Shalom in Geist,
Seele und Leib] geleitet werden.


==== Psalm 107:20
Er sandte sein Wort und heilte mich, er rettete [mich] aus meiner Grube.


==== 2. Timotheus 1:7
Denn Gott hat mir nicht einen Geist der Furchtsamkeit gegeben, sondern der Kraft
und der Liebe und der Zucht.


==== Jakobus 4:7
Ich widerstehe dem Teufel [ich stehe fest gegen ihn]!
Und er wird von mir fliehen (in Terror).

==== Jesaja 26:3
Du bewahrst mich in vollkommenem Frieden (Vollkommenheit), weil ich auf dich vertraue.


==== Philipper 2:9.10
Gott hat Jesus hoch erhoben und ihm den Namen verliehen, der über jeden Namen ist
[Deine Krankheit hat einen Namen. Jetzt sprich zu diesem Geist der Krankheit in Jesu
Namen und er muss gehen. Er wird bleiben, bis er sicher ist, Du wirst nicht
aufgeben durch Müdigkeit oder Unglauben.]


==== Zephaniah 3:17
Der HERR, mein Gott, ist *in meiner Mitte*, ein Held, der rettet (der heilt);
er freut sich über mich in Fröhlichkeit, er schweigt [in stiller Zufriedenheit]
in seiner Liebe [ist still und erwähnt nicht die Sünden der Vergangenheit,
noch erinnert er sich an sie], er jauchzt über mich mit Jubel.


==== Psalm 84:12
Kein Gutes wird der Herr mir vorenthalten, denn ich wandle in Lauterkeit.

==== Matthäus 12:36.37
...Für jedes Wort, das ich spreche, das keinem rechtmäßigen Zweck dient,
das unwirksam und deshalb moralisch nutzlos ist und keinen Nutzen bringt,
werde ich Rechenschaft geben müssen am Tag des Gerichts; denn aus meinen
Worten werde ich gerechtfertigt werden und aus meinen Worten werde ich verdammt werden.
(Dank sei Gott für Umkehr und das Blut Jesu!)


==== Psalm 91:9.10.16
Weil ich [gesagt habe]: "`Der HERR ist meine Zuflucht!`";
weil ich den Höchsten zu meiner Wohnung gesetzt [habe],
begegnet mir kein Unglück, und keine Plage naht meinem Zelt.
Gott sättigt mich mit *langem Leben* und lässt mich sein Heil [Heilung] schauen.


==== Johannes 16:23

...Ich versichere euch, aufs Ernsthafteste sage ich euch: Was ihr den Vater
bitten werdet in meinem Namen [darin liegt die ganze Autorität meiner Gottheit],
wird er euch geben.
...[Ich] bitte und bitte weiter und [ich] werde empfangen, sodass meine Freude
(Fröhlichkeit, Begeisterung) vollständig und komplett sei.


==== Jakobus 1:2-4.12
Ich halte es für lauter Freude... wann immer ich in Versuchungen jedweder Art
verwickelt bin oder darauf treffe oder in verschiedene Anfechtungen falle.
Ich weiß sicher und verstehe, dass die Anfechtungen und Prüfungen meines Glaubens
*Ausdauer* und *Standhaftigkeit* und *Geduld* hervorbringen.

Ich gestatte Ausdauer und Standhaftigkeit und Geduld, in mir gründlich zu wirken,
damit ich vollkommen und vollständig [ohne Makel] entwickelt sein werde
und es mir an nichts mangelt. Ich bin gesegnet (glücklich, ich werde beneidet),
wenn ich unter Anfechtungen geduldig bin, bei Versuchungen fest stehe,
denn nachdem ich bewährt bin, *werde* ich den Siegeskranz des Lebens empfangen,
den der Herr mir verheißen hat, weil ich ihn liebe.


==== Galater 6:9
...Ich werde im Gutestun nicht müde werden! Denn zur bestimmten Zeit werde
ich den Segen ernten, wenn ich nicht aufgebe.


==== Sprüche 6:2
Der Teufel versucht, mich durch die Worte meines Mundes zu verstricken;
[Ich bewache meinen Mund, sodass er nur mit dem übereinstimmt, was Gott sagt].


==== 1. Johannes 1:9
Wenn ich meine Sünden bekenne, ist er treu und gerecht, dass er meine Sünden
vergibt und mich reinigt von *jeder* Ungerechtigkeit.


==== Psalm 103:2-3
Preise den HERRN, meine Seele, und vergiss nicht alle seine Wohltaten!
Der da vergibt alle meine Sünde, der da *heilt alle meine Krankheiten.*


==== 5. Mose 7:14-15
Ich werde gesegnet sein vor allen Völkern... und der HERR wird *jede*
Krankheit von mir abwenden...

[quote, Larry S.]
--
*Erlebte Heilung in der Gegenwart*

"`Er hat mich von Krebs geheilt. Alle meine Ärzte sagen, ich bin ein Wunder.`"
--


==== 2. Korinther 4:13
...Ich habe *geglaubt*, darum habe ich *geredet*, so glaube auch ich [weil ich Tag
und Nacht über Gottes Wort meditiere/nachsinne] und darum rede ich auch...


[quote, Sharon B.]
--
*Erlebte Heilung in der Gegenwart*

"`2010 ist meine Tochter gestorben... Die Ärzte wollten, dass ich ihre Organe spende;
ich sagte:  `Das kann ich erst tun, wenn ich von Gott die Erlaubnis habe.`
...Und Gott hat sie uns lebendig zurückgegeben, ohne dass sie Schaden an
Körper oder Gehirn genommen hätte.`"
--


==== Römer 8:11
...der Geist dessen, der Jesus aus den Toten auferweckt hat, wohnt in mir;
der Christus Jesus aus den Toten auferweckt hat, wird auch meinen sterblichen
Leib lebendig machen [mich heilen] durch seinen in mir wohnenden Geist.


==== 1. Johannes 5:14.15
Und dies ist die Zuversicht, die ich in ihm habe, dass er mich hört,
wenn ich etwas nach seinem Willen bitte [Krankheit ist *nicht* in seinem Willen].
Und wenn ich *weiß*, dass er mich hört, was ich auch bitte, so weiß ich, dass
ich das Erbetene habe, das ich von ihm erbeten habe.


==== 1. Johannes 4:4
...der, welcher *in mir* ist, ist *größer* als der, welcher in der Welt ist.


==== Offenbarung 12:11
...Ich *überwinde* den Teufel [und seine Frucht der Krankheit] wegen des *Blutes*
des Lammes und wegen des Wortes meines Zeugnisses [jedes Mal wenn ich das Mahl nehme,
entferne ich die Fesseln der Krankheit Stück für Stück, mehr und mehr]...


==== Philipper 4:8
...alles, was wahr, alles, was ehrbar, alles, was gerecht, alles, was rein, alles,
was liebenswert, alles, was wohllautend ist, wenn es irgendeine Tugend und wenn es
irgendein Lob [gibt], das erwägt [ich richte mein Augenmerk auf diese Tatsachen und
nicht auf das Gegenteil]!


==== Matthäus 6:14.15
Denn wenn ich den Menschen ihre Vergehungen vergebe [ihre leichtsinnigen und vorsätzlichen
Sünden, sie wegtue, sie loslasse und allen Ärger aufgebe], so wird mein himmlischer
Vater auch mir vergeben; wenn ich aber den Menschen nicht vergebe, so wird mein
Vater meine Vergehungen [meine leichtsinnigen und vorsätzlichen Sünden]
auch nicht vergeben. [Vergebung ist eine Voraussetzung. Es ist keine Emotion oder ein
Gefühl, sondern eine Entscheidung. Sie basiert nicht darauf, dass jemand Vergebung
verdient; genauso wenig, wie ich Vergebung verdient hatte. Das bedeutet nicht,
ich muss der Person vertrauen. Sie muss das Vertrauen verdienen.
Trotzdem entscheide ich mich, in *sofortiger Vergebung* zu leben!]


==== 1. Johannes 4:17.18
...denn wie er ist, bin auch ich in dieser Welt. Furcht ist nicht in der Liebe,
sondern die vollkommene (reife) Liebe treibt die Furcht aus... Wer sich aber
fürchtet, ist nicht vollendet (gereift) in der Liebe
[die Liebe Gottes besiegt die Furcht].


==== Psalm 103:20
Preist den HERRN, ihr seine Engel, ihr Gewaltigen an Kraft, *Täter seines Wortes*,
dass man höre auf die Stimme seines Wortes [seine Verheißungen in *meinem* Mund]!


==== Jesaja 40:31
Weil ich auf den HERRN hoffe, gewinne ich neue Kraft: Ich hebe die Schwingen empor
wie die Adler, ich laufe und ermatte nicht, ich gehe und ermüde nicht.

==== Johannes 20:29
Jesus spricht: "`...Glückselig [sind], die nicht gesehen und [doch] geglaubt haben!`"
[Ich bin gesegnet, weil ich glaube, bevor ich sehe]!


==== Matthäus 9:27-30
Und als Jesus von dort weiterging, folgten ihm zwei Blinde.... Jesus spricht zu ihnen:
*Glaubt* ihr, dass ich dies tun kann?” Sie sagen zu ihm: "`*Ja*, Herr.`"
Dann rührte er ihre Augen an und sprach: "`Euch *geschehe* nach *eurem Glauben*!`"
[Mir geschehe nach meinem Glauben]!


==== Johannes 17:3
Dies aber ist das ewige Leben, dass ich dich, den allein wahren Gott,
und den du gesandt hast, Jesus Christus, erkenne [erfahre, erlebe].
[Jede Gabe Gottes wird mir geschenkt als ein Resultat einer großen Intimität,
die ich zu ihm entwickle].

==== Psalm 27:1
Der HERR ist mein Licht und mein Heil [Heilung, Befreiung, Schutz], vor wem
sollte ich mich fürchten?

==== Matthäus 6:10
Dein Reich komme; dein Wille geschehe, wie im Himmel so auch auf Erden
[es gibt keine Krankheit im Himmel]!

==== Johannes 14:12
Jesus sagt, wenn ich unerschütterlich an ihn glaube, werde ich die Werke tun,
die er tut, und ich werde größere als diese tun...


==== 5. Mose 3:22
*Ich fürchte nichts*! Denn der HERR, mein Gott, er ist es, der für mich kämpft.


==== Psalm 118:17
Ich werde nicht sterben, sondern leben und die Taten Jahs (Gottes) erzählen.


==== 1. Petrus 2:24
...durch dessen (Jesu) Striemen *wurde* ich geheilt.


[quote, Carleen R.]
--
*Erlebte Heilung in der Gegenwart*

"`Meine Schwester hatte vor vielen Jahren Eierstock- und Brustkrebs.
Durch Gnade und die Heilungskraft Gottes ist sie nun seit 23 Jahren krebsfrei!`"
--

==== Psalm 107:20
Er sandte sein Wort und heilte mich...


==== 5. Mose 28:1.2.7
Wenn ich der Stimme des HERRN, meines Gottes, genau gehorche,
dass ich darauf achte, all seine Gebote zu tun, die er... befiehlt,
dann wird der HERR, mein Gott, mich als höchste über alle Nationen der Erde stellen.
Und alle diese Segnungen werden über mich kommen und werden mich erreichen,
wenn ich der Stimme des HERRN, meines Gottes, gehorche.
Der HERR wird meine Feinde [Krankheit], die sich gegen mich erheben,
geschlagen vor mir dahingeben…


==== Psalm 92:15
Noch im Greisenalter gedeihe ich, bin ich saftvoll und grün
[und werde Frucht bringen]...


==== Römer 12:19
Ich räche mich nicht selbst. Ich überlasse das dem gerechten Zorn Gottes.


==== 1. Korinther 13:4-7.8
Ich bin langmütig und gütig; ich neide nicht; ich tue nicht groß,
ich blähe mich nicht auf. Ich benehme mich nicht unanständig, ich suche nicht
das Meine, ich lasse mich nicht erbittern, ich rechne Böses nicht zu,
ich freue mich nicht über die Ungerechtigkeit, sondern ich freue mich mit der
Wahrheit, ich gebe niemals auf, ich verliere nie den Glauben, ich bin immer
voller Hoffnung, in allen Umständen habe ich Geduld. Ich *versage nie!*


==== Psalm 41:4
Der HERR wird mich stützen [aufrechterhalten, erfrischen und stärken] auf dem
Krankenbett, er wandelt mein ganzes Lager um in meiner Krankheit
[er heilt mich vollständig von meiner Krankheit].


==== 1. Johannes 3:23
Und dies ist sein Gebot, dass ich an den Namen seines Sohnes Jesus Christus
glaube (alles glaube, wofür dieser Name steht) und meinen Nächten liebe...


==== 3. Johannes 1:2
In allen Dingen geht es mir wohl und ich werde in guter Gesundheit bleiben,
so wie es meiner Seele wohlgeht.


==== Matthäus 9:22
"`...Sei guten Mutes!... Dein Glaube hat dich geheilt.`"


==== Jakobus 2:17.18
...Mein Glaube ist, wenn er keine Werke (zugehörige Handlungen) hat,
in sich selbst tot. Ich werde meinen Glauben durch meine Werke
(zugehörige Handlungen) zeigen.


==== Psalm 52:2
Die Gnade Gottes [währt] den ganzen Tag [sie hält fortwährend an].


==== Lukas 18:1
Ich soll allezeit beten und nicht ermatten.


==== Lukas 4:18
"`Der Geist des Herrn ist auf mir, weil er mich gesalbt hat...; er hat mich gesandt,
Gefangenen Freiheit auszurufen und Blinden, dass sie wieder sehen,
Zerschlagene in Freiheit hinzusenden...`"

==== Jesaja 41:13
Denn der HERR, mein Gott, hält meine Rechte, der Herr spricht zu mir:
Fürchte dich nicht! Ich, ich helfe dir!

==== Epheser 2:8
Denn aus Gnade seid ihr errettet (geheilt) durch Glauben, und das nicht aus euch,
Gottes Gabe ist es.


== Segensgebet

Matthäus 18:19 sagt: "`Wiederum sage ich euch: Wenn zwei von euch auf der
Erde übereinkommen, irgendeine Sache zu erbitten, so wird sie ihnen werden von
meinem Vater, der in den Himmeln ist.`"

Ich stimme mit Dir in Jesu Namen in Bezug auf Deine Heilung überein
(nun sind wir zu zweit). *Du bist geheilt!*


Shalom und Liebe,

Sid Israel Roth
