[[faq]]
== Antworten auf verbreitete Fragen zu Heilung

=== Hat jeder die Gabe der Heilung?

Nicht jeder hat die Gabe der Heilung.
Aber gemäß Markus 16:18 kann jeder Gläubige "`...den Kranken die Hände auflegen
und sie werden gesund werden.`"


=== Welche Schritte sollte ich gehen, um die Gabe der Heilung zu erhalten?

Um die Gabe der Heilung zu erhalten, solltest Du in Heiligkeit gehen,
in Intimität mit Gott, über den Heilungsschriftstellen in diesem Buch
meditieren und Gott um diese Gabe bitten. Außerdem lege Deine Hände auf
Kranke und bete oft für sie. Die Art und Weise, wie die ersten Jünger
lernten, Wunder zu erleben, war, zu beobachten, was Jesus tat, und das
Gleiche zu tun. Finde jemanden mit der Gabe der Heilung und diene ihm,
"`trage seine oder ihre Taschen`". Mit anderen Worten: Biete ihnen Hilfe an,
sodass sie Dich lehren können.


=== Kann ich für meine eigene Heilung beten oder muss jemand anderes über mir beten?

Da jeder Gäubige die Hände auf Kranke legen kann (Markus 16:18),
bedeutet das, Du kannst die Hände auf dich selbst legen.
Folge diesen Schritten, als wenn Du für jemand anderes beten würdest:
Gehe in Heiligkeit und Intimität mit Gott und bekenne die Heilungsschriftstellen
in diesem Buch über Deinem Leben.


=== Warum sind viele Wunder heutzutage nicht sofort sichtbar oder vollständig, so wie es Jesu Wunder waren?

Nicht jede Heilung Jesu fand sofort statt. Die Bibel lehrt uns, wie er zweimal
für einen blinden Mann gebetet hat, damit dieser geheilt wurde (Markus 8:25).
Jesus hat verheißen, wir würden die gleichen Werke tun, die er tat, und sogar
größere (Johannes 14:12)! Wir kommen in eine Zeit in der Geschichte,
wo Gott uns so wie Jesus salben wird, und wir werden die gleichen Werke sehen und
größere. Sei nicht entmutigt, wenn Du keine sofortige Heilung erlebst.
Bete weiter und habe Glauben an Gott. Gott wird vielleicht seine Macht
durch eine Heilung an Stelle eines Wunders manifestieren.
Der Unterschied zwischen einer Heilung und einem Wunder:
Eine Heilung ist ein schrittweises Wunder, ein Wunder ist eine sofortige Heilung.


*Erlebte Heilung in der Gegenwart*

[quote, Rita L.]
"`Meine Tochter wurde gerettet, als ihre Organe versagt haben.
Gott hat die Kontrolle!`"


=== Warum werden manche Menschen geheilt und andere nicht?

Es kann viele Gründe geben, warum manche Menschen geheilt werden und
andere nicht. Manchmal ist der Grund einfach unvergebene Sünde oder
Unversöhnlichkeit. Ein anderer Grund ist, dass manche auf Grund bestehender
Symptome in ihrem Glauben wanken. Manchmal geben die Menschen einfach auf.
Aber wir sind berufen, nicht zu richten. Wir sind berufen, Gläubige zu sein.
Wir sollen Gott vertrauen und ihn nicht mit unserem begrenzten
Verständnis in Frage stellen. Wir sind verantwortlich für das,
was wir wissen, nicht für das was wir nicht wissen.


=== Muss man auf eine besondere Art beten, um Heilungswunder zu erleben?

Jesus hat in den Evangelien auf verschiedene Arten gebetet.
Lass den Heiligen Geist Dich leiten. Meditiere über den Heilungsschriftstellen
in diesem Buch. Lege Kranken die Hände auf und glaube.
Manchmal werden Menschen sofort durch ein Wunder geheilt und manchmal
werden sie schrittweise geheilt. Lass Dich nicht irritieren durch das,
was Du siehst, sondern lass Dich nur durch das Wort Gottes leiten.
Wenn Du gemeinsam mit Gläubigen Gebetswunder erleben kannst,
wird Dir das helfen, Deine Gabe wachsen zu lassen.


=== Lässt Gott jemals Menschen krank werden?

Gott lässt niemanden krank werden. Allerdings öffnen Sünde,
Flüche oder (über Generationen) vererbte Flüche die Tür für den Teufel,
Krankheit auf uns zu legen. Dankenswerterweise sagt Galater 3:13:
"`Christus hat uns losgekauft von dem Fluch des Gesetzes, indem er ein Fluch
für uns geworden ist; denn es steht geschrieben:
`Verflucht ist jeder, der am Holz hängt!` `"
Daher können wir Flüche durch Gebet brechen. Egal wodurch die Krankheit ausgelöst
wird, Jesus starb für alle unsere Leiden (Psalm 103:3).
Krankheit kommt nicht von Gott. Töten, Stehlen und Umbringen ist
das Werk des Teufels, wohingegen von Gott Leben im Überfluss kommt (Johannes 10:10).


=== Kann Gott mehr heilen als physische Erkrankungen (z.B. Gefühle oder Verhalten)?

Ja, Gott kann mehr heilen als körperliche Erkrankungen!
Er ist gekommen, damit Du Leben im Überfluss in Geist, Seele und Leib haben mögest.


=== Wie passt die moderne Medizin und das Gesundheitswesen zusammen mit Gottes Fähigkeit, Heilungswunder zu vollbringen?

Bete zuerst und wenn die Symptome ernst sind, geh zum Arzt.
Es ist keine mangelnder Glaube, zum Arzt zu gehen. Nur wenn Du eine Diagnose hast,
kannst Du das Problem im Gebet besser angehen.

Ich kämpfe gegen Krankheit auf jede erdenkliche Art. Gott nutzt Ärzte,
jedoch werden wir in göttlicher Gesundheit gehen, wenn unser Glaube entwickelt ist.
Es gibt keine Verdammnis in Jesus! Es ist einfacher, Glaube zu entwickeln,
wenn es Dir gut geht. Wenn dann die Symptome beginnen, sich zu manifestieren,
kannst Du sie davon abhalten, sich einzunisten.


=== Ist es wahr, dass Vergebung Teil des Heilungsprozesses ist?

Ja, Vergebung ist Teil des Heilungsprozesses.
Es wird gesagt: "`Unversöhnlichkeit trinkt das Gift, das Du Deinem Feind geben wolltest.`"
Vergebung ist eine Entscheidung. Der Person zu vertrauen, der Du vergibst,
kann Zeit in Anspruch nehmen, jedoch sollten wir immer in sofortiger Vergebung leben.


=== Was sind die größten Hindernisse, ein Heilungswunder zu empfangen?

Die zwei größten Hindernisse, ein Heilungswunder zu empfangen,
sind unvergebene Sünde und unterentwickelter Glaube.
Erinnere Dich: Glaube ist eine Gabe,die jeder Gläubige empfängt,
aber er ist auch eine Frucht, die entwickelt werden muss.


=== Wenn jemand über mir betet und ich werde geheilt, ist die Person, die gebetet hat, oder Gott verantwortlich für die Heilung?

Gott, der durch die für Heilung betende Person gewirkt, erhält alle Ehre!


=== Was antworte ich jemandem, der mich fragt, warum Gott ihn nicht geheilt hat?

CAUTION: Gib ihnen eine Kopie dieses Buches!
Jesus hat den Preis für ihre Heilung bezahlt.
Daher sind sie bereits geheilt und so, wie sie die Frucht des
Glaubens entwickeln und widerstehen, so muss der Teufel fliehen.

Weil es in der Ewigkeit keine Zeit gibt, liegt das Timing für die Heilung bei Gott.
Der Glaube ist unser Anteil. Der Teufel liebt es, Krankheiten zu verursachen
und uns dazu zu bringen, die Güte Gottes anzuzweifeln. Achte darauf,
niemals auf Gott wütend zu werden. Unsere Aufgabe ist es, mit ihm tief
vertraut zu werden. Durch Glaube und Geduld wird die Heilung kommen.


=== Sollte ich mir wegen falscher Wunder Sorgen machen?

Die Bibel warnt uns vor falschen Wundern, besonders in den letzten Tagen.
Die zwei wichtigsten Schlüssel, um die wahren von den falschen zu trennen,
sind in diesen letzten Tagen _Heiligkeit_ und _Israel_.

Menschen, die die Gabe der Heilung anwenden, jedoch keinen geheiligten Lebensstil
oder einen unbiblischen Blick auf die Juden und Israel haben,
öffnen sich selbst für böse Geister. Der Geist Gottes wird auch der Heilige
Geist genannt. In Israel hat das Evangelium begonnen und nach Israel
wird Jesus zurückkehren. Die Verheißung von 1. Mose 12:3 ist wahr:
Gott wird die segnen, die das jüdische Volk segnen, und wird die verfluchen,
die das jüdische Volk verfluchen. Joel 4:1-2 sagt uns, dass die Sünde,
die das letzte Gericht freisetzen wird, die ist, dass die Menschen
"`sein Land (Israel) aufteilen.`" Gott hat einen Pachtvertrag für das
Land mit dem jüdischen Volk (Psalm 105:8-11). Die dort gebrauchten Wort
sind "`für immer`", "`1000 Generationen`" und "`ewig`".
Das ist ein wasserdichter Vertrag! Die Berufung der Gläubigen aus den
Nationen ist, "`die Juden zur Eifersucht zu reizen`" (Römer 11:11),
indem wir ihnen das Evangelium bringen. Wenn der Eine Neue Mensch
geformt ist (Jude und Heide sind eins im Messias), wird er Leben aus den Toten
freisetzen (Römer 11:15).

*Erlebte Heilung in der Gegenwart*

[quote, Barry L.]
"`Meine Mutter wurde von Eierstockkrebs vor ungefähr 20 Jahren geheilt
und ist heute am Leben, um Ihre himmlische Heilung zu verkünden.
Was kann ich sagen, als Ihn zu preisen, der uns zuerst geliebt hat!`"


=== Warum spielt es eine Rolle, dass Gott heutzutage immer noch Wunder vollbringt?

Ein Wunder beweist, dass das Reich Gottes auf die Erde gekommen ist.
Wenn Menschen Wunder sehen, öffnet es ihr Herz für das Hören des Evangeliums.
So haben Jesus, die Apostel und die ersten Jünger Mengen versammelt,
die die Gute Nachricht gehört hatten. Heilungswunder sind genauso ein
Werkzeug zur Evangelisation, wie sie ein Nutzen sind für die, die Heilung empfangen.


=== Gibt es eine Schriftstelle, die ich sofort parat haben sollte, wenn ich von Krankheit angegriffen werde?

Ich liebe Matthäus 6:10: "`Dein Reich komme. Dein Wille geschehe, wie im Himmel
so auf Erden.`"

Im Himmel gibt es keine Krankheit. Wir sind berufen, mit Gott und seinem Wort
übereinzustimmenden und nicht mit dem Teufel und seinen Lügen.
Mit wem stimmst Du überein? Wir sollen nicht die Symptome verleugnen,
sondern ihnen ihr Recht streitig machen, die Lügensymptome des Feindes
auf der Erde zu verbreiten. Wir sind berufen, zu bleiben!
