[[Introduction]]
== Schriften der Heilung

Autor: {Author} +
Übersetzung: {Translation} +
Lektorat: {Editor}

[quote, Sid Roth]
"`Ich habe von Genesis bis zur Offenbarung die kraftvollsten Heilungsschriftstellen
an einem Ort zusammengetragen.
Meditiere über ihnen und bete sie täglich über Deinem Leben!`"


== Ein Wort von Sid

Ich habe bemerkt, dass Heilung und Glaube für die meisten Gläubigen Geheimnisse sind.
Obwohl es viele Bücher zu beiden Themen gibt, herrscht auf diesen Gebieten großes Unverständnis.
Das sollte nicht so sein!

=== Glaube &#8212; der Schlüssel, um himmlischen Lohn zu empfangen

Hebräer 11:6 lehrt uns,

"`Ohne Glauben aber ist es unmöglich, [ihm] wohlzugefallen;
denn wer Gott naht, muss glauben, dass er ist und denen, die ihn suchen, ein Belohner sein wird.`"

Ohne Glaube können wir Gott nicht gefallen! Damit wir irgendetwas im Königreich empfangen können,
angefangen mit der Errettung, brauchen wir Glauben. Wenn Du an Jesus glaubst, hast Du Glauben.
Die Frage ist, wie nutzt Du ihn?

Glaube ist keine mentale Sache. Es ist ein Handeln, basierend auf der Tatsache des Kreuzes,
das ruft: "`Es ist vollbracht`". Biblischer Glaube glaubt, dass die Heilung bereits da ist,
bevor Du sie sehen kannst. Gott ist ein Belohner derer, die ihn gewissenhaft suchen.
Er möchte sein Volk mit Heilung belohnen!
Der Messias hat einen hohen Preis bezahlt, damit Du in ganzheitlicher göttlicher Gesundheit
gehen kannst. Es gibt einen Schlüssel, dass Du die Kraft des Himmels persönlich erlebst:
Du musst lernen, Deinen Glauben lebendig werden zu lassen.


=== Heilung &#8212; Der Wille Gottes, offenbart durch den Messias

[quote, Sharon H.]
--
*Erlebte Heilung in der Gegenwart*

"`Vor zwölf Jahren haben mir die Ärzte noch 3 Wochen zu leben gegeben...
Gott hatte bessere Pläne für mein Leben.`"
--

Wir lesen in Apostelgeschichte 10:38: "`Jesus von Nazareth, wie Gott ihn mit Heiligem
Geist und mit Kraft gesalbt hat, der umherging und wohltat und alle heilte, die von dem Teufel
überwältigt waren; denn Gott war mit ihm.`"

Wenn Jesus umhergegangen ist, gute Taten getan und alle geheilt hat, zeigt uns das,
dass Heilung Gottes Wille ist.
Alles, was Jesus tat, zeigt uns, wer Gott ist, wie er ist und was sein Wille ist.
Gottes Wille für Dein Leben ist Heilung!

=== Meine Entdeckung &#8212; Die übernatürliche Vorlage der Bibel

Jesus hat uns gezeigt, was "`normal`" bedeutet. Obwohl Heilung und Glaube etwas Geheimnisvolles
für viele Gläubige ist - vielleicht aufgrund von Missverständnissen, Missbrauch,
Kontroversen etc. -, ist Heilung normal, normal, wie es die Bibel definiert.
Dieses Buch soll Dir helfen, dass die Normalität des Himmels in Dein Leben kommt,
ins Leben Deiner Familie und Deiner Freunde; ja, Du sollst sogar erleben,
wie Gottes Heilungskraft durch Dich freigesetzt wird und andere berührt.

Ich habe meine eigenen Nachforschungen mit der Thematik der Heilung und des Glaubens
vor über 40 Jahren begonnen. Womit habe ich angefangen?
Mit dem Studium der Schrift. Es dauerte nicht lange, bis ich überwältigt war
von der Tatsache, dass es Gottes Wille ist, Krankheit und Leiden zu heilen.

- Zuerst habe ich alle Glaubens- und Heilungsschriftstellen, die ich finden konnte, aufgeführt.
- Danach habe ich die übriggebliebenen Verse personalisiert.
- Schlussendlich habe ich begonnen, darüber zu meditieren.

Diese Entdeckung hat mir geholfen, eine auf der Bibel basierende Vorlage zu erstellen,
die Dir praktisch helfen wird, die übernatürliche Heilungskraft in Deinem Leben zu erfahren.

Vor Kurzem habe ich mit einer orthodoxen jüdischen Frau gesprochen,
die nun an Jesus glaubt, inspiriert durch eines meiner jüdischen evangelistischen
Bücher mit dem Titel "`Sie dachten bei sich selbst`".
Ihre einzige Lehre war unsere Fernsehshow "`It’s Supernatural!`".
Sie war schockiert, als ich ihr sagte, manche Christen glauben,
seit die Apostel gestorben sind, gebe es keine Heilung mehr.
Wunder haben aber nicht aufgehört. Gott heilt heute immer noch.

== Deine Transformation beginnt jetzt

Diese Buch enthält meine persönliche Liste an Heilungs-Schriftstellen.
Wenn Du über die Verheißungen in diesem Buch und über die beiden
verfügbaren Audio-CDs meditierst, werden sie anfangen,
sich von Deinem Kopf in Dein Herz zu bewegen. Eine Transformation findet statt.
Das, was ein Gedanke in Deinem Kopf war, wird jetzt Glaube in Deinem Herzen.
Er wird Dein Denken vollständig verändern, sodass Du eine ganz andere Einstellung
zur Krankheit bekommst und auch anders auf sie reagierst.
Glaube und Heilung werden für Dich nicht länger ein Geheimnis sein!

[quote, Julia R.]
--
*Erlebte Heilung in der Gegenwart*

"`Geheilt von Krebs: zwei Mal! Jahwe Rapha! Unser Arzt!`"
--

[quote, April K.]
--
*Erlebte Heilung in der Gegenwart*

"`Ich habe meine Hände auf eine junge Frau gelegt und für sie gebetet...
Sie hat buchstäblich die Gegenwart [Gottes] im Raum gespürt...
Jetzt ist sie geheilt und die Ärzte können keine Spur von Schaden finden.`"
--
